# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-15 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='trigger',
            field=models.ManyToManyField(blank=True, to='app01.Trigger', verbose_name='触发器列表'),
        ),
    ]
