# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20171215_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triggerexpression',
            name='data_clac_args',
            field=models.CharField(help_text='若是多个参数，用,号分开。', max_length=64, verbose_name='函数传入参数'),
        ),
        migrations.AlterField(
            model_name='triggerexpression',
            name='data_clac_func',
            field=models.CharField(choices=[('avg', 'Average'), ('max', 'Max'), ('hit', 'Hit'), ('avg', 'Average'), ('last', 'Last')], max_length=32, verbose_name='数据处理方式'),
        ),
        migrations.AlterField(
            model_name='triggerexpression',
            name='specified_index_key',
            field=models.CharField(blank=True, max_length=32, verbose_name='只监控专门指定的指标key'),
        ),
    ]
