# Generated by Django 2.0.6 on 2018-06-20 15:27

from django.db import migrations, models
import utils.upload_file


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=utils.upload_file.upload_to, verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=utils.upload_file.upload_to, verbose_name='封面图'),
        ),
    ]
