# Generated by Django 2.0.6 on 2018-06-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_auto_20180613_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(max_length=200, upload_to='static/Courses/images/%Y/%m', verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='download',
            field=models.FileField(max_length=200, upload_to='static/Courses/resource/%Y/%m', verbose_name='资源文件'),
        ),
    ]
