# Generated by Django 2.0.6 on 2018-06-21 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0003_auto_20180621_1319'),
        ('Courses', '0002_auto_20180620_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Organization.CourseOrg', verbose_name='机构'),
        ),
    ]
