# Generated by Django 2.0.6 on 2018-06-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_course_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='其它', max_length=20, verbose_name='课程类别'),
        ),
    ]
