# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-21 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='adderss',
            new_name='address',
        ),
    ]
