# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-23 09:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_auto_20180323_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
    ]
