# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=32)),
                ('pwd', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktest.UserType'),
        ),
    ]
