# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-27 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_heroinfo_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroinfo',
            name='age',
            field=models.IntegerField(),
        ),
    ]
