# Generated by Django 2.0.6 on 2018-06-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('famel', '女')], default='male', max_length=6, verbose_name='性别'),
        ),
    ]
