# Generated by Django 2.0.6 on 2018-06-20 15:27

from django.db import migrations, models
import utils.upload_file


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.upload_file.upload_to, verbose_name='轮播图片'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='/static/image/default.png', max_length=200, null=True, upload_to=utils.upload_file.upload_to, verbose_name='用户头像'),
        ),
    ]
