# Generated by Django 2.0.6 on 2018-06-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20180612_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='static/images/Banner/%Y/%m/%d/', verbose_name='轮播图片'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='image/default.png', max_length=200, upload_to='static/images/User/images/%Y/%m', verbose_name='用户头像'),
        ),
    ]
