# Generated by Django 2.0.6 on 2018-06-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20180613_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='static/Banner/%Y/%m/%d/', verbose_name='轮播图片'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='image/default.png', max_length=200, upload_to='static/User/images/%Y/%m', verbose_name='用户头像'),
        ),
    ]
